name = "vault-worker"
main = "worker/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "KV"
id = "95dc8c3e4e4f4f798183a30a3d99a4b0"
preview_id = "local-dev-kv-preview"

[[r2_buckets]]
binding = "R2"
bucket_name = "vault-files"

[vars]
JWT_SECRET = "super-secret-vault-key-123"
INITIAL_USERS = '[{"email":"admin", "password":"password123"}]'

[site]
bucket = "./dist"
